### ISSUE TITLE
a标签链接 点击 无反应

### ISSUE THREAD

**Issue by 82318179** [LulumiProject/lulumi-browser#49]
1 a标签链接 点击 无反应；正常应该是弹出一个新tab来浏览新闻，结果 怎么点击都没有反应
2 右下角一直 提示  loading playbooks.... 
![1](https://user-images.githubusercontent.com/25976728/73933963-85241a80-4918-11ea-9d98-a4ade2c84c69.png)

**Comment by qazbnm456** [comment]
Thanks for trying out! I'll look into it as soon as possible. 😄
Besides, the taskbar below is still under development, so you can just ignore it for now.
